#!/bin/bash

v4l2-ctl --set-ctrl brightness=30
v4l2-ctl --set-ctrl contrast=5
v4l2-ctl --set-ctrl saturation=83
v4l2-ctl --set-ctrl white_balance_temperature_auto=0
v4l2-ctl --set-ctrl white_balance_temperature=4500
v4l2-ctl --set-ctrl power_line_frequency=2
v4l2-ctl --set-ctrl sharpness=25
v4l2-ctl --set-ctrl backlight_compensation=0
v4l2-ctl --set-ctrl exposure_auto=1
v4l2-ctl --set-ctrl exposure_absolute=5
v4l2-ctl --set-ctrl focus_auto=0
v4l2-ctl --set-ctrl focus_absolute=15
v4l2-ctl --set-ctrl zoom_absolute=0

python send_video.py | python fdsrcrtsp.py